import { Product } from '../types/product';

export const getMockProducts = async (): Promise<Product[]> => {
  return [
    {
      id: 1,
      nome: 'Monitor 24"',
      categoria: 'Eletrônico',
      preco: 899.90,
      descricao: 'Monitor Full HD com painel IPS',
      imagem: '/images/monitor.png',
    },
    {
      id: 2,
      nome: 'Teclado Mecânico',
      categoria: 'Acessórios',
      preco: 299.99,
      descricao: 'Teclado com switches blue e iluminação RGB',
      imagem: '/images/teclado.png',
    },
    {
      id: 3,
      nome: 'Mouse sem Fio',
      categoria: 'Acessórios',
      preco: 49.99,
      descricao: 'Mouse sem fio com iluminação RGB',
      imagem: '/images/mouse.png',
    },
    {
      id: 4,
      nome: 'Cadeira Gamer',
      categoria: 'Acessórios',
      preco: 599.99,
      descricao: 'Cadeira gamer com ajuste de altura e iluminação RGB',
      imagem: '/images/cadeira.png',
    },
    {
      id: 5,
      nome: 'Produto 5',
      categoria: 'Categoria 5',
      preco: 500.00,
      descricao: 'Descrição do Produto 5',
      imagem: '/images/produto5.png',
    },
    {
      id: 6,
      nome: 'Produto 6',
      categoria: 'Categoria 6',
      preco: 600.00,
      descricao: 'Descrição do Produto 6',
      imagem: '/images/produto6.png',
    },
    {
      id: 7,
      nome: 'Produto 7',
      categoria: 'Categoria 7',
      preco: 700.00,
      descricao: 'Descrição do Produto 7',
      imagem: '/images/produto7.png',
    },
    {
      id: 8,
      nome: 'Produto 8',
      categoria: 'Categoria 8',
      preco: 800.00,
      descricao: 'Descrição do Produto 8',
      imagem: '/images/produto8.png',
    },
    {
      id: 9,
      nome: 'Produto 9',
      categoria: 'Categoria 9',
      preco: 900.00,
      descricao: 'Descrição do Produto 9',
      imagem: '/images/produto9.png',
    },
    {
      id: 10,
      nome: 'Produto 10',
      categoria: 'Categoria 10',
      preco: 1000.00,
      descricao: 'Descrição do Produto 10',
      imagem: '/images/produto10.png',
    },
    {
      id: 11,
      nome: 'Produto 11',
      categoria: 'Categoria 11',
      preco: 1100.00,
      descricao: 'Descrição do Produto 11',
      imagem: '/images/produto11.png',
    },
    {
      id: 12,
      nome: 'Produto 12',
      categoria: 'Categoria 12',
      preco: 1200.00,
      descricao: 'Descrição do Produto 12',
      imagem: '/images/produto12.png',
    },
    {
      id: 13,
      nome: 'Produto 13',
      categoria: 'Categoria 13',
      preco: 1300.00,
      descricao: 'Descrição do Produto 13',
      imagem: '/images/produto13.png',
    },
    {
      id: 14,
      nome: 'Produto 14',
      categoria: 'Categoria 14',
      preco: 1400.00,
      descricao: 'Descrição do Produto 14',
      imagem: '/images/produto14.png',
    },
    {
      id: 15,
      nome: 'Produto 15',
      categoria: 'Categoria 15',
      preco: 1500.00,
      descricao: 'Descrição do Produto 15',
      imagem: '/images/produto15.png',
    },
    {
      id: 16,
      nome: 'Produto 16',
      categoria: 'Categoria 16',
      preco: 1600.00,
      descricao: 'Descrição do Produto 16',    
      imagem: '/images/produto16.png',
    }, 
    {
      id: 17,
      nome: 'Produto 17',
      categoria: 'Categoria 17',
      preco: 1700.00,
      descricao: 'Descrição do Produto 17',
      imagem: '/images/produto17.png',
    },
    {
      id: 18,
      nome: 'Produto 18',
      categoria: 'Categoria 18',
      preco: 1800.00,
      descricao: 'Descrição do Produto 18',
      imagem: '/images/produto18.png',
    },
    {
      id: 19,
      nome: 'Produto 19',
      categoria: 'Categoria 19',
      preco: 1900.00,
      descricao: 'Descrição do Produto 19',
      imagem: '/images/produto19.png',
    },
    {
      id: 20,
      nome: 'Produto 20',
      categoria: 'Categoria 20',
      preco: 2000.00,
      descricao: 'Descrição do Produto 20',
      imagem: '/images/produto20.png',
    }
    
  ];
};
